[package]
name = "cstat2csv"
version = "1.0.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
csv = "1.3.1"
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["derive"] }
